# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
